### PR TITLE
set CodeGenerationOptions

### PR DESCRIPTION
**Pull request by serii833**
feature:
possibility to set CodeGenerationOptions in order to specify options for generating code format.

### CODE REVIEW

**Comment by flonou** [comment]
Hi! Can you add some tests for this? That would also serve as an example of what it enables

**Comment by flonou** [comment]
Seems like this also solves #16 ?
Could you add a third test with a generation option different from none or default value too ? (To make sure that the option is taken into account)

**Comment by serii833** [comment]
> Seems like this also solves #16 ?

I would say this PR solves only part of #16. 
in #16 he talks about passing xsd as string and getting generated code from `GeneratorFacade`.
For now it is possible to feed xsd string instead of file in `GeneratorParams` but still no way to get generated code as string directly from `GeneratorFacade`. 
In tests I had to use `Generator` class directly and convert CodeDom namespace to code text inside tests.
I was thinking about getting generated code as string from `GeneratorFacade` (would be nice for testing) but it requires a bit of refactoring. didn't want to clutter this PR

**Comment by flonou** [comment]
Looks good to me, thanks you for your contribution and answers !

**Pull request merged**
